name: Build

## workflow will trigger by deploy workflow on main branch
on:
  workflow_call:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  GITHUB_REGISTRY_URL: ghcr.io
  GITHUB_CONTAINER_NAME: ${{ github.repository }}
  GO_VERSION: 1.22.1

jobs:
  cardinal:
    name: World Engine - Cardinal
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      ## Execute makefile
      - name: Run Make
        working-directory: world-engine/cardinal
        run: make
      ## Set Docker metadata
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITHUB_REGISTRY_URL }}/${{ env.GITHUB_CONTAINER_NAME }}/cardinal
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha
      ## Login into GCR / Github Packages
      - name: Docker - Auth to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      ## Push build image to GCR / Github Packages
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./world-engine/cardinal
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  godot:
    name: Godot - HTML Export
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      ## Execute makefile
      - name: Copy Godot Export HTML data
        run: |
          ## godot-web_export directory on the main branch has changed recently ## need to update the copy path command accordingly.
          # (prev) cp -r ./godot/web_export .github/docker-godot-webexport/

          mkdir -p .github/docker-godot-webexport/web_export
          cp -rf ./ArcaneReveal* .github/docker-godot-webexport/web_export/

          ls -lah .github/docker-godot-webexport/web_export
      ## Set Docker metadata
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITHUB_REGISTRY_URL }}/${{ env.GITHUB_CONTAINER_NAME }}/godotexport
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha
      ## Login into GCR / Github Packages
      - name: Docker - Auth to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      ## Push build image to GCR / Github Packages
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .github/docker-godot-webexport/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
