name: Deploy

## workflow will need manual trigger from actions page
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Railway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Railway CLI
        run: |
          bash <(curl -fsSL cli.new)
      - name: Install Redis-CLI
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: 7
          auto-start: "false"
      - name: Install Postgresql client-only
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
      - name: Cardinal - Shutdown Previous Deployment
        working-directory: cardinal
        run: |
          ## Get Cardinal Latest Deployment ID
          DEPLOYMENT_ID=$(curl --location 'https://backboard.railway.app/graphql/v2' \
            --header 'Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{"query":"query deployments($projectId: String!, $environmentId: String!, $serviceId: String!) {\n  deployments(\n    first: 1\n    input: {\n      projectId: $projectId\n      environmentId: $environmentId\n      serviceId: $serviceId\n    }\n  ) {\n    edges {\n      node {\n        id\n        staticUrl\n      }\n    }\n  }\n}",
            "variables":{"projectId":"${{ vars.RAILWAY_PROJECT_ID }}","environmentId":"${{ vars.PROD_RAILWAY_ENVIRONMENT_ID }}","serviceId":"${{ vars.RAILWAY_CARDINAL_SERVICE_ID }}"}}' | jq -r '.data.deployments.edges[].node.id')

          ## Remove Deployment
          curl --location 'https://backboard.railway.app/graphql/v2' \
            --header 'Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{"query":"mutation deploymentRemove($id: String!) {\n  deploymentRemove(id: $id)\n}","variables":{"id":"'${DEPLOYMENT_ID}'"}}'
      - name: Clear Up Redis
        run: |
          sleep 10
          redis-cli -h ${{ secrets.PROD_REDIS_HOST }} -p ${{ secrets.PROD_REDIS_PORT }}  <<EOF
          AUTH ${{ secrets.PROD_REDIS_PASSWORD }}
          FLUSHALL
          keys *
          EOF
      - name: Cardinal - Run Make
        working-directory: world-engine/cardinal
        run: make
      - name: Cardinal - Up New Deployment
        env:
          RAILWAY_TOKEN: ${{ secrets.PROD_RAILWAY_TOKEN }}
        working-directory: world-engine/cardinal
        run: |
          railway up --service Cardinal --environment production
      - name: Cardinal Healthcheck
        run: |
          curl -X POST --max-time 10 --retry 20 --retry-delay 5 --retry-max-time 300 ${{ vars.PROD_CARDINAL_HEALTHCHECK }} -d "{}"
      - name: Remove Nakama Database (Railway)
        run: |
          PGPASSWORD=${{ secrets.PROD_RAILWAY_POSTGRES_PASSWORD }} psql -h ${{ secrets.PROD_RAILWAY_POSTGRES_HOST }} -U ${{ secrets.PROD_RAILWAY_POSTGRES_USER }} -p ${{ secrets.PROD_RAILWAY_POSTGRES_PORT }} -d railway -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
      - name: Restart Nakama Services (Railway)
        run: |
          ## Get NAKAMA Latest Deployment ID
          DEPLOYMENT_ID=$(curl --location 'https://backboard.railway.app/graphql/v2' \
            --header 'Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{"query":"query deployments($projectId: String!, $environmentId: String!, $serviceId: String!) {\n  deployments(\n    first: 1\n    input: {\n      projectId: $projectId\n      environmentId: $environmentId\n      serviceId: $serviceId\n    }\n  ) {\n    edges {\n      node {\n        id\n        staticUrl\n      }\n    }\n  }\n}",
            "variables":{"projectId":"${{ vars.RAILWAY_PROJECT_ID }}","environmentId":"${{ vars.PROD_RAILWAY_ENVIRONMENT_ID }}","serviceId":"${{ vars.RAILWAY_NAKAMA_SERVICE_ID }}"}}' | jq -r '.data.deployments.edges[].node.id')

          ## RESTART Deployment
          curl --location 'https://backboard.railway.app/graphql/v2' \
            --header 'Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{"query":"mutation deploymentRestart($id: String!) {\n  deploymentRestart(id: $id)\n}","variables":{"id":"'${DEPLOYMENT_ID}'"}}'
      - name: Godot - Copy files
        run: |
          cp -r ./godot/web_export .github/docker-godot-webexport/
          ls -lah .github/docker-godot-webexport/web_export
      - name: Godot - Up New Deployment
        env:
          RAILWAY_TOKEN: ${{ secrets.PROD_RAILWAY_TOKEN }}
        working-directory: .github/docker-godot-webexport/
        run: |
          railway up --service ArcaneReveal-client --environment production
